# Generated by Django 3.2 on 2021-05-31 05:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 10, 34, 59, 242298), null=True)),
                ('check', models.BigIntegerField(null=True)),
                ('covid', models.BigIntegerField(null=True)),
                ('pneum', models.BigIntegerField(null=True)),
                ('normal', models.BigIntegerField(null=True)),
                ('other', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Xray_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50, null=True)),
                ('xray', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.xray')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('age', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('institute', models.CharField(choices=[('1', 'SPIT'), ('2', 'VJTI'), ('3', 'TATA'), ('4', 'Reliance'), ('5', 'serum')], max_length=1, null=True)),
                ('profession', models.CharField(choices=[('1', 'doctor'), ('2', 'nurse'), ('3', 'radiologist'), ('4', 'Pharmacy'), ('5', 'other')], max_length=1, null=True)),
                ('country', models.CharField(choices=[('1', 'India'), ('2', 'Australia'), ('3', 'NewZealand'), ('4', 'China'), ('5', 'Britain'), ('6', 'America')], max_length=1, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('Contact', models.BigIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
