# Generated by Django 3.2 on 2021-06-03 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 12, 11, 7, 569173), null=True),
        ),
    ]
