# Generated by Django 3.2 on 2021-06-03 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_mcount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 12, 46, 19, 669717), null=True),
        ),
    ]
