# Generated by Django 3.2 on 2021-06-03 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20210603_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mcount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 16, 10, 49, 4764), null=True),
        ),
    ]
