# Generated by Django 3.2 on 2021-06-03 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20210603_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 16, 14, 36, 279286), null=True),
        ),
    ]
