# Generated by Django 5.2.6 on 2025-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('empname', models.CharField()),
                ('empsalary', models.FloatField()),
            ],
        ),
    ]
