# Generated by Django 5.2.6 on 2025-09-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empname',
            field=models.CharField(max_length=200),
        ),
    ]
