# Generated by Django 5.2.6 on 2025-09-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_empname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empsalary',
            field=models.FloatField(default=0),
        ),
    ]
