# Generated by Django 5.2.6 on 2025-09-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_empsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
