# Generated by Django 5.2.6 on 2025-09-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_alter_employee_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empsalary',
        ),
    ]
