# Generated by Django 5.2.6 on 2025-09-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_employee_empsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empsalary',
            field=models.FloatField(default=None),
        ),
    ]
