# Generated by Django 5.2.6 on 2025-09-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_alter_employee_empsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empsalary',
            field=models.FloatField(default=0.0),
        ),
    ]
