# Generated by Django 5.2.6 on 2025-09-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_employee_id_alter_employee_empid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
