# Generated by Django 5.2.6 on 2025-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0004_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(default=0)),
                ('empname', models.CharField()),
                ('empsalary', models.IntegerField()),
            ],
        ),
    ]
