# Generated by Django 5.2.6 on 2025-09-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
